# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e27e9c7038b648b94fa287c2f3fe4a313b50b86e39d4191158262b17c3b3acada1b55254948558352b74400e6211030edcbab84017641320b0a6f2da438441c

test:
  secret_key_base: 712de36050d271ca7e488a60f2c87aeeb559d0ce75d7e8e16d86fe42c4c054973a615b8512fe652cdf1e24dba3a184a6425081c24408936edb23062c9915edc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
